import os

OPENAI_MODEL_NAME = "gpt-5.4"
OPENAI_API_TIMEOUT_SECONDS = 300
OPENAI_API_MAX_RETRIES = 3
OPENAI_REASONING_SUMMARY = "auto"
OPENAI_SCREENSHOT_DETAIL = "original"
OPENAI_AUTO_ACKNOWLEDGE_SAFETY_CHECKS = os.environ.get(
    "OPENAI_AUTO_ACKNOWLEDGE_SAFETY_CHECKS",
    "0",
).lower() in {"1", "true", "yes", "on"}
SCROLL_PIXELS_PER_CLICK = int(os.environ.get("SCROLL_PIXELS_PER_CLICK", "100"))
