from __future__ import annotations

from typing import Protocol, Tuple


class Mouse(Protocol):
    def position(self) -> Tuple[int, int]: ...
    def move_to(self, x: int, y: int, *, duration_ms: int = 0) -> None: ...
    def click(self, *, button: str = "left", clicks: int = 1) -> None: ...
    def down(self, *, button: str = "left") -> None: ...
    def up(self, *, button: str = "left") -> None: ...
    def scroll(self, *, dx: int = 0, dy: int = 0) -> None: ...
    def drag(self, start: Tuple[int, int], end: Tuple[int, int], *, steps: int = 1, delay_ms: int = 0) -> None: ...

